config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :attendances
    resources :pictures, only: [:new, :create]
  end

  namespace :admin do
    root 'admin#index'
    resources :users, :events
  end

  resources :users
  resources :charges, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  has_many :guest_attendances, foreign_key: 'guest_id', class_name: "Attendance"
  has_many :admin_events, foreign_key: 'admin_id', class_name: "Event"
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    if !current_user?(@user.id)
      flash[:error] = "You are the wrong user."
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
    if !current_user?(@user.id)
      flash[:error] = "You are the wrong user."
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if !current_user?(@user.id)
      flash[:error] = "You are the wrong user."
      redirect_to root_path
    else
      if @user.update(user_params)
        flash[:success] = "Your profile has been updated."
        redirect_to user_path(@user.id)
      else
        render 'edit'
      end
    end
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description)
  end

end

app/helpers/users_helper.rb
module UsersHelper 

  def current_user?(user)
    user == current_user.id
  end

end

app/views/users/edit.html.erb
<div class="container-fluid ">
  <h2 class="mt-5">Edit my profile</h2>

  <div class="container-fluid">
    <%= form_for(current_user, url: user_path(current_user), method: :put) do |f| %>
    <div class="field">
      <%= f.label "Firstname" %><br />
      <%= f.text_field :first_name, autofocus: true, autocomplete: :first_name %>
    </div><br />
    <div class="field">
      <%= f.label "Lastname" %> <br />
      <%= f.text_field :last_name, autocomplete: :last_name %>
    </div><br />
    <div class="field">
      <%= f.label "Description" %> <br />
      <%= f.text_area :description, autocomplete: :description %>
    </div><br />
    <div class="actions">
      <%= f.submit "Update", class:"btn btn-outline-primary btn-sm" %>
    </div>
  <% end %>
  </div>

  <div class="mt-5">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/users/show.html.erb
<div class="card">
  <div class="card-header">
    Your dashboard
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @current_user.full_name%></h5>
    <p class="card-text"><%=@current_user.description%></p>
    <%=link_to "Edit profile", edit_user_path, type:"button", class: "btn btn-outline-primary btn-sm" %>
    <%=link_to "Edit login", edit_user_registration_path,type:"button", class:"btn btn-outline-primary btn-sm"%>
  </div>
</div>
<div class="container-fluid text-center">
  <p>Contact here: <%=@current_user.email %></p>
</div>

<div class="card">
  <div class="card-header">
    Event(s) created by <%=current_user.full_name%> 
  </div>
  <div class="card-body">
    <% Event.where(admin_id: current_user.id).each do |event| %>
      <h5 class="card-title"><%= link_to event.title, event_path(event.id)%></h5>
    <% end %>
  </div>
</div>
<div class="card">
  <div class="card-header">
    Event(s) attended by <%=current_user.full_name%>
  </div>
  <div class="card-body">
    <% Attendance.where(guest_id: current_user.id).each do |attendance| %>
      <h5 class="card-title"><%= link_to attendance.event.title, event_path(attendance.event.id)%></h5>
    <% end %>
  </div>
</div>