config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :attendances
    resources :pictures, only: [:new, :create]
  end

  namespace :admin do
    root 'admin#index'
    resources :users, :events
  end

  resources :users
  resources :charges, only: [:new, :create]
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :picture
  has_many :attendances
  has_many :guests, class_name: "User", through: :attendances
  belongs_to :admin, class_name: "User" 
  validates :start_date, presence: true
  validate :start_must_be_future

  validates :duration, presence: true
  validate :duration_5
  validate :duration_positive

  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, inclusion: { in: 1..1000}
  validates :location, presence: true


  def start_must_be_future
    return unless start_date 
    errors.add(:start_date, "ne doit pas être passée") unless start_date > Time.now
  end

  def duration_5
    return unless duration
    errors.add(:duration, "doit être un multiple de 5") unless (duration % 5) == 0
  end
  
  def duration_positive
    return unless duration
    errors.add(:duration, "doit être supérieur à 0") unless duration > 0
  end

  def end_date
    start_date + (duration*60)
  end
end
 

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Your event has been created."
      redirect_to event_path(@event.id)
    else
      messages = []
      if @event.errors.any? 
        @event.errors.full_messages.each do |message| 
          messages << message
        end 
        flash[:error] = "You failed, find the following errors :#{messages.join(" ")}"
        render 'new'
      end
    end
  end

  def index
    @event = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
    #if !current_user?(@event.admin)
    #  flash[:error] = "You are the wrong user."
    #  redirect_to root_path
    #end
  end

  def update
    @event = Event.find(params[:id])
    #if !current_user?(@event.admin)
    #  flash[:error] = "You are the wrong user."
    #  redirect_to root_path
    #else
      if @event.update(update_event)
        flash[:success] = "Your event has been updated."
        redirect_to event_path(@event.id)
      else
        render 'edit'
      end
    #end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:success] = "Your event was successfully destroyed !"
      redirect_to root_path
    else
      render'destroy'
    end
  end

  private

  def event_params
    params.require(:events).permit(:title, :location, :duration, :description, :price, :start_date, :admin_id, :picture)
  end

  def update_event
    params.require(:event).permit(:title, :location, :duration, :description, :price, :start_date, :admin_id)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_banner.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Eventbrite</h1>
    <p>Participate to the best events of your city</p><br />
    <%=link_to "New event", new_event_path, type:"button", class: "btn btn-outline-primary" %>
  </div>
</div>

app/views/events/_card.html.erb
<div class= "container-fluid"><br>
  <h1 class="text-center">All events</h1><br>
  <div class="row" style= "display: flex; flex-flow: row wrap; justify-content: space-around">
    <% Event.order("start_date ASC").all.each do |event| %> 
      <div class="card" style="width: 25rem" >
        <div class="card-body" style="background-color: #f0ad4e">
          <h5 class="card-title text-center" ><%= event.title %></h5>
          <h6 class="card-text text-center" ><%= event.start_date.strftime("%d/%m/%Y %H:%M") %></h6><br />
          <div class="row" style= "display: flex; text-align: center; flex-basis: auto; align-items: flex-end">
          <%if event.picture.attached?%>
            <%= image_tag event.picture, alt: 'picture', class: "card-img-left" %>
          <%else%>
            <img src="https://images.unsplash.com/photo-1492684223066-81342ee5ff30?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="picture-event" class="card-img-left"></img>
          <%end%>

            <p class="card-text" >- <%= event.location %></p><br />
          </div>
          <br />
          <a href="<%=event_path(event)%>" class="btn btn-outline-primary">See event</a>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br />

app/views/events/_famous.html.erb
<div class= "container fluid text-center">
  <div class="row" style= "display: flex; flex-flow: row wrap; justify-content: space-around">
    <div class="card" style="width: 15rem" >
      <div class="card-body" style="background-color:white">
        <img class="card-img-left" src="https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png"/>
        <h5 class="card-title" >I am Batman<br /></h5>
        <p class="text-muted">100 k followers</p>
        <br />
        <a href="#" class="btn btn-outline-primary">Follow</a>
      </div>
    </div>
    <div class="card" style="width: 15rem" >
      <div class="card-body" style="background-color:white">
        <img class="card-img-left" src="https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png"/>
        <h5 class="card-title" >I am Batman<br /></h5>
        <p class="text-muted">100 k followers</p>
        <br />
        <a href="#" class="btn btn-outline-primary">Follow</a>
      </div>
    </div>
    <div class="card" style="width: 15rem" >
      <div class="card-body" style="background-color:white">
        <img class="card-img-left" src="https://www.pinclipart.com/picdir/middle/34-345142_suit-boys-avatar-icon-png-clipart.png"/>
        <h5 class="card-title text-center" >Organisateur 3<br /></h5>
        <p class="text-muted">4599 followers</p>
        <br />
        <a href="#" class="btn btn-outline-primary">Follow</a>
      </div>
    </div>
    <div class="card" style="width: 15rem" >
      <div class="card-body" style="background-color:white">
        <img class="card-img-left" src="https://cdn.icon-icons.com/icons2/1736/PNG/512/4043255-beard-hipster-male-man_113243.png"/>
        <h5 class="card-title text-center" >Organisateur 4<br /></h5>
        <p class="text-muted">100 followers</p>
        <br />
        <a href="#" class="btn btn-outline-primary">Follow</a>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container-fluid text-center">
  <div class="texte-bienvenue">
    <h1>Edit the event</h1>
  </div>
  <%= form_for @event do |f| %>
    <div class="form-group">
      <label> Title of the event</label>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label> Description</label>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label> Location</label>
      <%= f.text_field :location, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label> Start date</label>
      <%= f.datetime_field :start_date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label> Duration (in minutes)</label>
      <%= f.text_field :duration, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label> Price</label>
      <%= f.number_field :price, class: 'form-control' %>
    </div>
    <div class="form-group">
    <button type="submit" class="btn" style="background-color: #ffc0cb">Update your event</button>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<%= render 'banner'%>

<%= render 'card' %>

<%= render 'famous'%>

app/views/events/new.html.erb
<div class="mt-lg-5 mt-1 mb-3 pt-0">
  <div class="col-12 d-flex align-items-center justify-content-center">
    <div class="col-lg-4 col-12 box-shadow-2 p-0">
      <div class="card border-grey border-lighten-3 m-0">
        <div class="card-header border-0">
          <div class="text-center mb-1">
            <h3>Create a new event</h3>        
          </div>
        </div>
        <div class="card-content">
          <div class="card-body">
            <%= form_for(:events,  url:(events_path), action: 'create', method: :post) do |f| %>

              <div class="field">
                <%= f.hidden_field :admin_id, :value => current_user.id %>
              </div><br />

              <fieldset class="form-group position-relative">
                <%= f.label :title %><br />
                <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "form-control" %>
              </fieldset>

              <fieldset class="form-group position-relative">
                <%= f.label :description %>
                <%= f.text_area :description, autocomplete: "description", class: "form-control" %>
              </fieldset>

              <fieldset class="form-group position-relative">
                <%= f.label :location %>
                <%= f.text_field :location, autocomplete: "location", class: "form-control" %>
              </fieldset>

              <fieldset class="form-group position-relative">
                <%= f.label :start_date %>
                <%= f.datetime_field :start_date, autocomplete: "start_date", class: "form-control" %>
              </fieldset>

              <fieldset class="form-group position-relative">
                <%= f.label "Duration (in minutes)" %>
                <%= f.text_field :duration, autocomplete: "start_date", placeholder: "It must be a multiple of 5", class: "form-control" %>
              </fieldset>

              <fieldset class="form-group position-relative">
                <%= f.label :price %>
                <%= f.number_field :price, autocomplete: "price", class: "form-control" %>
              </fieldset>

              <fieldset class="form-group position-relative">
                <%= f.label :picture %><br>
                <%= f.file_field :picture, autocomplete: "picture" %>
              </fieldset>
                 

              <div class="form-group ">
                <div class="row justify-content-center">
                  <div class="col-12">
                    <%= f.submit "Register", class: "col-12 btn btn-primary mr-1 mb-1" %>
                  </div>
                </div>
              </div>
              <hr>
              <div class="text-center">
                <div class="col-12 float-sm-left text-center pt-2 mb-2">
                  <a class="card-link" href="<%= root_path%>">Back</a>
                </div>
              </div>
            <% end %>       
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="card-deck">
  <div class="card">
    <div class="card-header row mr-0">
      <ul class="navbar-nav nav-left header-left">
        Event no. <%= @event.id %>
      </ul>
      <ul class="navbar-nav class="header-right"">
        <%if current_user != @event.admin%>
          <% if @event.guests.include?(current_user) %>
            You are attending this event
          <%else%>
            <%=link_to "Attend event",  new_event_attendance_path(event_id: @event.id), class: "btn btn-outline-primary btn-sm" %>
          <%end%>
        <%else%>   
          <%=link_to "See details", event_attendances_path(event_id: @event.id), class: "btn btn-outline-primary btn-sm" %>
        <% end %>
      </ul>
    </div>
    <div class="card-body">
      <ul class="card-body-left">
        <h5 class="card-title"><%= @event.title %></h5>
        <p class="card-text">Already <%= @event.guests.count %> attendees !</p>
        <p class="card-text">Price : <%= @event.price %> € VAT excl.</p>
        <p class="card-text">Location : <%= @event.location %></p>
        <p class="card-text">Start date : <%= @event.start_date.strftime("%d/%m/%Y %H:%M") %></p>
        <p class="card-text">End date : <%= @event.end_date.strftime("%d/%m/%Y %H:%M") %></p>
        <p class="card-text">Event's description : <%= @event.description %></p>
      </ul>
    </div>
  </div>

  <div class="card">
    <ul class="img-event">
      <%if @event.picture.attached?%>
        <%= image_tag @event.picture, alt: 'picture', class: "card-img img-fluid", style:"max-height: 25rem" %>
      <%else%>
          <p class="no-img-event">=== There is no picture for this event ===</p>
      <%end%>
    </ul>
  </div>
</div>
  <div class="container-fluid text-center">
    <div class="card-img">
      <%if current_user == @event.admin%>
        <p> Want to change picture ?</p>
        <%= form_tag event_pictures_path(@event), multipart: true do %>
          <%= file_field_tag :picture %>
          <%= submit_tag "Update", class:"btn btn-outline-primary btn-sm"%>
        <% end %>
      <% else %>
        <p>Contact admin here : <%=@event.admin.email %></p>
      <% end %>
    </div>
  </div>


 
      