config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :attendances
    resources :pictures, only: [:new, :create]
  end

  namespace :admin do
    root 'admin#index'
    resources :users, :events
  end

  resources :users
  resources :charges, only: [:new, :create]
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @event = Event.find(params[:id])
  end

  def create
    # Amount in cents
   @event = Event.find(params[:id])
   @amount = @event.price * 100

   customer = Stripe::Customer.create({
     email: params[:stripeEmail],
     source: params[:stripeToken],
   })
 
   charge = Stripe::Charge.create({
     customer: customer.id,
     amount: @amount,
     description: 'Rails Stripe customer',
     currency: 'eur',
   })

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
    
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @amount/100 %>€</strong>!</h2>

<%= current_user.id %></br>
<%= @customer_id %></br>
<%= @event.id %>


  <%= form_tag event_attendances_path(event_id: @event.id), method: "post" do %>

    <%= hidden_field_tag :guest_id, current_user.id %>
    <%= hidden_field_tag :event_id, @event.id %>
    <%= hidden_field_tag :customer_id, @customer_id %>

    <%= submit_tag "Confirm and back to main page", class: "btn btn-dark text-light" %>
  <% end %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= @event.price %>€</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount=<%= @event.price * 100 %>
          data-locale="auto"></script>
 
<%= hidden_field_tag :id, @event.id %>
<% end %>