config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :attendances
    resources :pictures, only: [:new, :create]
  end

  namespace :admin do
    root 'admin#index'
    resources :users, :events
  end

  resources :users
  resources :charges, only: [:new, :create]
end

app/views/layouts/_flash.html.erb
<div class="flash">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> flash">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small unique-color-primary">
  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5 footer-header">
    <!-- Grid row -->
    <div class="row mt-3">
      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold footer-text footer-header">Eventbrite Lite</h6>
        <hr class="footer-line accent-2 mb-4 mt-0 d-inline-block mx-auto footer-text" style="width: 60px;">
        <p>Welcome on Eventbrite, THE website to know the best events coming in your town. So enjoy !</p>
      </div>
      <!-- Grid column -->
      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold footer-text footer-header">Products</h6>
        <hr class="footer-line accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="<%=new_event_path%>" class="footer-text">New event</a>
        </p>
        <p>
          <a href="<%=root_path%>" class="footer-text">All events</a>
        </p>
        <p>
          <% if user_signed_in? %>
            <%= link_to "#{current_user.email}", user_path(current_user), class:"footer-text"%>
          <%end%>
        </p>
        <p>
          <a href="#!" class="footer-text">Get premium</a>
        </p>
      </div>
      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold footer-text footer-header">Useful links</h6>
        <hr class="footer-line accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="#!" class="footer-text">Team</a>
        </p>
        <p>
          <a href="#!" class="footer-text">Career</a>
        </p>
        <p>
          <a href="#!" class="footer-text">Legal Notice</a>
        </p>
        <p>
          <a href="#!" class="footer-text">Languages</a>
        </p>
      </div>
      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold footer-text footer-header">Contact</h6>
        <hr class="footer-line accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Tombouctou</p>
        <p>event@brite.com</p>
        <p>+ 01 02 03 04 05</p>
        <p>+ 02 03 04 05 06</p>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3 footer-text">© 2020 Copyright: THP - 
    <a href="#" class = "footer-text">Raphaël & Agnès</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Event Brite Lite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav nav-left">
      <li class="nav-item active">
        <%=link_to "Home", root_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "New event", new_event_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "#{current_user.email}", user_path(current_user), class:"nav-link"%>
        <%end%>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <% if user_signed_in? %>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Settings
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <ul>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
              <%= link_to "Edit login", edit_user_registration_path, class: "dropdown-item" %>
            </ul>
          </div>
        <% else %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Login/ Sign up
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <ul>
                <%=link_to "Login", new_user_session_path, class:"dropdown-item" %>
                <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item"%>
              </ul>
            </div>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventBriteLite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/lux/bootstrap.min.css" rel="stylesheet" integrity="sha384-oOs/gFavzADqv3i5nCM+9CzXe3e5vXLXZ5LZ7PplpsWpTCufB7kqkTlC9FtZ5nJo" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>EventBriteLite</title>
  </head>

  <body>
    
    <%= render 'layouts/header'%>
    <%= render 'layouts/flash'%>
    <%= yield %>
    <%= render 'layouts/footer'%>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>